project:
  type: website
  output-dir: _site

website:
  title: "Tom Stafford"
  description: "Personal website of Tom Stafford"
  site-url: https://tomstafford.github.io
  repo-url: https://github.com/tomstafford/tomstafford.github.io
  favicon: favicon.png
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
      - href: publications.qmd
      - href: done.qmd
      - href: news.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
