---
title: "Papers"
---

[Google scholar profile](https://scholar.google.co.uk/citations?hl=en&user=bMEna2UAAAAJ&view_op=list_works&sortby=pubdate), ORCID ID : [0000-0002-8089-9479](http://orcid.org/0000-0002-8089-9479)

# Theme highlights

--------------------

## Data intensive psychology: 

-    Panagiotidi, M., Zavlis, O., Jones, M., & Stafford, T. (2024). [The three-dimensional community structure of attention-deficit hyperactivity disorder (ADHD) traits captured by the Adult ADHD Self-Report Scale: An exploratory graph analysis](https://onlinelibrary.wiley.com/doi/full/10.1002/mpr.1997). International Journal of Methods in Psychiatric Research, e1997. <https://doi.org/10.1002/mpr.1997> [[preprint](https://psyarxiv.com/sakn9)]

-   Stafford, T., and Vaci, N. (2022). [Maximizing the potential of digital games for understanding skill acquisition](https://doi.org/10.1177/09637214211057841). Current Directions in Psychological Science, 31(1), 49-55.  <https://doi.org/10.1177/09637214211057841> [[web/mobile version](https://journals.sagepub.com/doi/full/10.1177/09637214211057841)]

-   Bannard, C., Leriche, M., Bandmann, O., Brown, C., Ferracane, E., Sánchez-Ferro, A., Obeso, J., Redgrave, P. and Stafford, T. (2019). [Reduced habit-driven errors in Parkinson's Disease](https://www.nature.com/articles/s41598-019-39294-z). Nature Scientific Reports 9(1), 3423. [[pre-print](https://psyarxiv.com/b25tf/)]

- Vardal, O., Karapanagiotidis, T., Stafford, T., Drachen, A., & Wade, A. (2025). [Unsupervised identification of internal perceptual states influencing psychomotor performance](https://doi.org/10.1016/j.neuroimage.2025.121134). NeuroImage, 310, 121134. https://doi.org/10.1016/j.neuroimage.2025.121134
[[preprint](https://www.biorxiv.org/content/10.1101/2023.09.08.556817v2.abstract)]

## Metaresearch

-   Jones, A., Petrovskaya, E., & Stafford, T. (2024). [Exploring the multiverse of analysis options for the alcohol Stroop](https://link.springer.com/article/10.3758/s13428-024-02377-5). Behavior Research Methods, 56(4), 3578-3588. [[preprint](https://psyarxiv.com/prfu2/)]

-   Stafford T, Rombach I, Hind D et al. Where next for partial randomisation of research funding? The feasibility of RCTs and alternatives [version 2; peer review: 3 approved]. Wellcome Open Res 2024, 8:309 (<https://doi.org/10.12688/wellcomeopenres.19565.2>)

-   Bendiscioli, Sandra; Firpo, Teo; Bravo-Biosca, Albert; Czibor, Eszter; Garfinkel, Michele; Stafford, Tom; et al. (2022): [The Experimental Research Funder's Handbook](https://rori.figshare.com/articles/report/The_experimental_research_funder_s_handbook_final_version_/19459328) (Revised edition, June 2022, ISBN 978-1-7397102-0-0). Research on Research Institute. Report. https://doi.org/10.6084/m9.figshare.19459328.v2

-   Silberzahn, R. et al (2018). [Many analysts, one dataset: Making transparent how variations in analytical choices affect results](http://journals.sagepub.com/doi/full/10.1177/2515245917747646). Advances in Methods and Practices in Psychological Science, 1(3), 337-356. 

    -   See also : '[Science isn't broken](https://fivethirtyeight.com/features/science-isnt-broken/)' and the [interactive visualisation by Mat Evans which allowed us to find an important confound in the source data](https://github.com/mathewzilla/redcard/blob/master/Crowdstorming_visualisation.ipynb).

    -   Ploner, S., & Stafford, T. (2021). [How analysis strategy affects analysis results: Assessing results space and structure of Silberzahn et al. (2018) through model specification](https://osf.io/preprints/psyarxiv/nzskm). Retrieved from osf.io/preprints/psyarxiv/b2hm7

## Decision making & reasoning

- Stafford, T., Zhu, J., & Dommett, K. (2024, December 31). Quantifying belief in the rationality of others: the Faith in Reason scale. Working Paper. <https://doi.org/10.31234/osf.io/umwxj>

-   Stafford, T., Pirrone, A., Croucher, M., and Krystalli, A. (2020). [Quantifying the benefits of using decision models with response time and accuracy data](https://link.springer.com/article/10.3758/s13428-020-01372-w). Behaviour Research Methods, 52, 2142--2155. [doi.org/10.3758/s13428-020-01372-w](https://doi.org/10.3758/s13428-020-01372-w) (pre-print, [web/mobile version](https://idiolect.org.uk/papers/stafford2020/))

- Boag, R. J., Innes, R. J., Stevenson, N., Bahg, G., Busemeyer, J. R., Cox, G. E., ... & Forstmann, B. U. (2025). [An expert guide to planning experimental tasks for evidence-accumulation modeling](https://doi.org/10.1177/25152459251336127). Advances in Methods and Practices in Psychological Science, 8(2), 25152459251336127. <https://doi.org/10.1177/25152459251336127>

-   Brand, C. O., Brady, D., & Stafford, T. (2023, June 27). [The Ideological Turing Test: a behavioural measure of open-mindedness and perspective-taking](https://psyarxiv.com/2e9wn). https://doi.org/10.31234/osf.io/2e9wn

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2023). [DeliData: A dataset for deliberation in multi-party problem solving](https://dl.acm.org/doi/10.1145/3610056). Proceedings of the ACM on Human-Computer Interaction, CSCW. <https://doi.org/10.1145/3610056> [[arXiv](https://arxiv.org/abs/2108.05271)]

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2022). [What makes you change your mind? An empirical investigation in online group decision-making conversations](https://www.delibot.xyz/publications/). arXiv preprint [arXiv:2207.12035](https://arxiv.org/abs/2207.12035)

    -   -   See also: [delibot.xyz](https://www.delibot.xyz/)

-   De Kock, C., Stafford, T., & Vlachos, A. (2022). [How to disagree well: Investigating the dispute tactics used on Wikipedia](https://arxiv.org/abs/2212.08353). In Y. Goldberg, Z. Kozareva, & Y. Zhang (Eds.), Proceedings of the 2022 Conference on Empirical Methods in Natural Language Processing (pp. 3824–3837). Association for Computational Linguistics. https://doi.org/10.18653/v1/2022.emnlp-main.252

# Chronological

## In press, and under review

- Copeland, A., Dora, J., King, K., Stafford, T., & Field, M. (in press). Value-based decision-making in daily tobacco smokers following experimental manipulation of mood. *Experimental and Clinical Psychopharmacology* [preprint](https://osf.io/preprints/psyarxiv/5w4ap_v1)

- Lee, J., Zhu, X., Karadzhov, G., Stafford, T., Vlachos, A., & Lee, D. (2025). [Collaborative Evaluation of Deepfake Text with Deliberation-Enhancing Dialogue Systems](https://arxiv.org/abs/2503.04945). arXiv preprint arXiv:2503.04945.

- Zhu, X., Zhang, C., Stafford, T., Collier, N., & Vlachos, A. (2024). Conformity in Large Language Models. arXiv preprint [arXiv::2410.12428](https://doi.org/10.48550/arXiv.2410.12428)

- Boag, R. J., Innes, R. J., Stevenson, N., Bahg, G., Busemeyer, J. R., Cox, G. E., … Forstmann, B. (2024, July 2). [An expert guide to planning experimental tasks for evidence accumulation modelling](https://osf.io/preprints/psyarxiv/snqgp). 

-   Brand, C. O., Brady, D., & Stafford, T. (2023, June 27). [The Ideological Turing Test: a behavioural measure of open-mindedness and perspective-taking](https://psyarxiv.com/2e9wn). https://doi.org/10.31234/osf.io/2e9wn

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2022). [What makes you change your mind? An empirical investigation in online group decision-making conversations](https://www.delibot.xyz/publications/). arXiv preprint [arXiv:2207.12035](https://arxiv.org/abs/2207.12035)

    -   -   See also: [delibot.xyz](https://www.delibot.xyz/)


## 2025

-   Zhu, J., Dommett, K., & Stafford, T. (2025). [What makes online political ads unacceptable? Interrogating public attitudes to inform regulatory responses](https://doi.org/10.1057/s41599-025-05114-1 ). Humanities and Social Sciences Communications, 12, 806. https://doi.org/10.1057/s41599-025-05114-1 

- Vardal, O., Karapanagiotidis, T., Stafford, T., Drachen, A., & Wade, A. (2025). [Unsupervised identification of internal perceptual states influencing psychomotor performance](https://doi.org/10.1016/j.neuroimage.2025.121134). NeuroImage, 310, 121134. https://doi.org/10.1016/j.neuroimage.2025.121134
[[preprint](https://www.biorxiv.org/content/10.1101/2023.09.08.556817v2.abstract)]


## 2024

- Karadzhov, G. M., Vlachos, A., & Stafford, T. (2024). The effect of diversity on group decision-making. Proceedings of the Annual Meeting of the Cognitive Science Society, 46(0). https://escholarship.org/uc/item/6685n22z. arXiv preprint [arXiv:2402.01427](https://arxiv.org/abs/2402.01427).

-   Dommett, K., Mensah, S. A., Zhu, J., & Stafford, T. (2024). [Understanding the communicative strategies used in online political advertising and how the public views them](https://doi.org/10.1177/13691481241287177). The British Journal of Politics and International Relations, 0(0). https://doi.org/10.1177/13691481241287177

-   Jones, A., Petrovskaya, E., & Stafford, T. (2024). [Exploring the multiverse of analysis options for the alcohol Stroop](https://link.springer.com/article/10.3758/s13428-024-02377-5). Behavior Research Methods, 56(4), 3578-3588. [[preprint](https://psyarxiv.com/prfu2/)]

-  Stafford, T., Gordon, H., Zhu, J., & Dommett, K. (2024). [Online political adverts: The effect of disclosures and opportunities for clandestine campaigning](https://onlinelibrary.wiley.com/doi/10.1111/pops.13034). Political Psychology, 00, 1–27. <https://doi.org/10.1111/pops.13034> 

-    Panagiotidi, M., Zavlis, O., Jones, M., & Stafford, T. (2024). [The three-dimensional community structure of attention-deficit hyperactivity disorder (ADHD) traits captured by the Adult ADHD Self-Report Scale: An exploratory graph analysis](https://onlinelibrary.wiley.com/doi/full/10.1002/mpr.1997). International Journal of Methods in Psychiatric Research, e1997. <https://doi.org/10.1002/mpr.1997> [[preprint](https://psyarxiv.com/sakn9)]

-   Adinugroho, I., Stafford, T., & Bentall, R. (2024). [The correlation between conspiracy mentality and vaccine intentions is moderated by social events: Evidence from longitudinal data during COVID-19 pandemic in the UK](https://www.sciencedirect.com/science/article/pii/S0264410X24005103). Vaccine, 42(16), 3607-3614. <https://doi.org/10.1016/j.vaccine.2024.04.071>  [[preprint](https://osf.io/preprints/psyarxiv/5wcnz/)]

-   Copeland, A., Stafford, T., & Field, M. (2024). [Value-based decision-making in regular alcohol consumers following experimental manipulation of alcohol value](https://www.sciencedirect.com/science/article/pii/S0306460324001187). Addictive Behaviors, 156, 108069. <https://doi.org/10.1016/j.addbeh.2024.108069> [[preprint](https://osf.io/wcks6/)]

- Stafford, T., Zhu, J., & Dommett, K. (2024, December 31). [Quantifying belief in the rationality of others: the Faith in Reason scale](https://doi.org/10.31234/osf.io/umwxj). Working paper. <https://doi.org/10.31234/osf.io/umwxj>

## 2023

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2023). [DeliData: A dataset for deliberation in multi-party problem solving](https://dl.acm.org/doi/10.1145/3610056). Proceedings of the ACM on Human-Computer Interaction, CSCW. https://doi.org/10.1145/3610056 [[arXiv](https://arxiv.org/abs/2108.05271)]

-   Stafford T, Rombach I, Hind D et al. (2023) [Where next for partial randomisation of research funding? The feasibility of RCTs and alternatives](https://wellcomeopenresearch.org/articles/8-309/v1) Wellcome Open Res 2023, 8:309 (https://doi.org/10.12688/wellcomeopenres.19565.1)

-   Farag, Y., Brand, C., Amidei, J., Piwek, P., Stafford, T., Stoyanchev, S., & Vlachos, A. (2022). Opening up Minds with Argumentative Dialogues. In Y. Goldberg, Z. Kozareva, & Y. Zhang (Eds.), Findings of the Association for Computational Linguistics: EMNLP 2022 (pp. 4569–4582). Association for Computational Linguistics. https://doi.org/10.18653/v1/2022.findings-emnlp.335

-   Dommett, K., Mensah, S. A., Zhu, J., Stafford, T., & Aletras, N. (2023). [Is There a Permanent Campaign for Online Political Advertising? Investigating Partisan and Non-Party Campaign Activity in the UK between 2018--2021](https://www.tandfonline.com/doi/full/10.1080/15377857.2023.2175102). Journal of Political Marketing, 1-19.

-   Varbanov V., Overton, P., and Stafford, T. (2023). [ADHD and ASD traits are indirectly associated with sensory changes through anxiety](https://link.springer.com/article/10.1007/s12144-022-04217-1) Curr Psychol (2023). <https://doi.org/10.1007/s12144-022-04217-1> [[preprint](https://psyarxiv.com/dchbs)].

## 2022

-   Vardal, O., Bonometti, V., Drachen, A., Wade, A., & Stafford, T. (2022). [Mind the gap: Distributed practice enhances performance in a MOBA game](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0275843). Plos one, 17(10), e0275843.

-   Brand, C. O., & Stafford, T. (2022). [Using dialogues to increase positive attitudes towards COVID-19 vaccines in a vaccine-hesitant UK population](https://royalsocietypublishing.org/doi/full/10.1098/rsos.220366). Royal Society Open Science, 9(10), 220366.

-   Copeland, A., Stafford, T., Acuff, S.F., Murphy, J.G. and Field, M. (in press). [Behavioral economic and value-based decision-making constructs that discriminate current heavy drinkers versus people who reduced their drinking without treatment](https://psyarxiv.com/5jhdg/). Psychology of Addictive Behaviors.

-   Bendiscioli, Sandra; Firpo, Teo; Bravo-Biosca, Albert; Czibor, Eszter; Garfinkel, Michele; Stafford, Tom; et al. (2022): [The Experimental Research Funder's Handbook](https://rori.figshare.com/articles/report/The_experimental_research_funder_s_handbook_final_version_/19459328) (Revised edition, June 2022, ISBN 978-1-7397102-0-0). Research on Research Institute. Report. https://doi.org/10.6084/m9.figshare.19459328.v2

-   Copeland et al (in press). Methodological issues with value-based decision-making (VBDM) tasks: the effect of trial wording on evidence accumulation outputs from the EZ drift-diffusion model. Cogent.

-   Stafford, T. (in press). [Evidence for the rationalisation phenomenon is exaggerated](https://psyarxiv.com/aygh6/). Behavioural and Brain Sciences (commentary)

-   Stafford, T., and Vaci, N. (2022). [Maximizing the potential of digital games for understanding skill acquisition](https://doi.org/10.1177/09637214211057841). Current Directions in Psychological Science, 31(1), 49-55.  <https://doi.org/10.1177/09637214211057841> [[web/mobile  version](https://journals.sagepub.com/doi/full/10.1177/09637214211057841)]

-   Pirrone, A., Reina, A, Stafford, T., Marshall, J.A.R., and Gobet, F. (2022). [Magnitude-sensitivity: Rethinking decision-making](https://www.sciencedirect.com/science/article/pii/S1364661321002618?casa_token=W5lKMgVueasAAAAA:GDwwQu4GBq4QtdbTWvjt7Y6-OY9kr7tgT0nGjQ1nu8a74laE5TCtmRotkpw5vQO6nQ8q14gH). Trends in Cognitive Sciences, 26(1), 66-80 [[OA version here](https://www.giovannireina.com/pdf/pirrone-TiCS2022.pdf)]


## 2021

-   Stafford, T. and Brand, C.O. (2021). [Commercial involvement in academic publishing is key to research reliability and should face greater public scrutiny](https://osf.io/preprints/metaarxiv/rjmvh). Evidence submitted to the House of Common Science and Technology Committee inquiry on reproducibility and research integrity.

-   Copeland, A., Stafford, T., and Field, M. (2021). Recovery from addiction: A synthesis of perspectives from behavioral economics, psychology, and decision modeling. In The Handbook of Alcohol Use (pp. 563-579). Academic Press.

-   Brand, C. O. and Stafford, T. (2021). Review 1: "Information Delivered by a Chatbot Has a Positive Impact on COVID-19 Vaccines Attitudes and Intentions." Rapid Reviews COVID-19. <https://doi.org/10.1162/2e3983f5.237d4808>

-   Ploner, S., & Stafford, T. (2021). [How analysis strategy affects analysis results: Assessing results space and structure of Silberzahn et al. (2018) through model specification](https://osf.io/preprints/psyarxiv/b2hm7). Retrieved from osf.io/preprints/psyarxiv/b2hm7

## 2020

-   Stafford, T., Pirrone, A., Croucher, M., and Krystalli, A. (2020). [Quantifying the benefits of using decision models with response time and accuracy data](https://link.springer.com/article/10.3758/s13428-020-01372-w). Behaviour Research Methods, 52, 2142--2155. [doi.org/10.3758/s13428-020-01372-w](https://doi.org/10.3758/s13428-020-01372-w) (pre-print, [web/mobile version](https://idiolect.org.uk/papers/stafford2020/))

    -   See also the interactive data explorer: sheffield-[university.shinyapps.io/decision_power](https://sheffield-university.shinyapps.io/decision_power/)

-   Dhir, N., Edman, M., Sanchez Ferro, A., Stafford, T., and Bannard, C. (2020). [Identifying robust markers of Parkinson's Disease in typing behaviour using a CNN-LSTM network](https://www.aclweb.org/anthology/2020.conll-1.47/). In Proceedings of Conference on Computational Natural Language Learning (CoNLL 2020).

-   Panagiotidi, M., Overton, P. and Stafford, T. (2020). [The relationship between sensory processing sensitivity and Attention Deficit Hyperactivity Disorder traits: a spectrum approach](https://www.sciencedirect.com/science/article/pii/S0165178120331383). Psychiatry Research, 293, 113477.

-   Scaife, R., Stafford, T., Bunge, A., and Holroyd, J. (2020). [To blame? The effects of moralized feedback on implicit racial bias](https://www.collabra.org/article/10.1525/collabra.251/). Collabra: Psychology, 6(1), 30. DOI: http://doi.org/10.1525/collabra.251

-   Pirrone, A., Illin, J., Stafford, T., Milne, E. (2020). [A diffusion model decomposition of orientation discrimination in children with Autism Spectrum Disorder](https://www.tandfonline.com/eprint/VIIZBcGgYpItKcCGw27I/full). European Journal of Developmental Psychology, 17, 2, 213-230.

-   Williams, L., Butler, J., Thirkettle, M., Stafford, T., Quinlivan, B., MacGovern, E., ... and Hutchinson, M. (2020). [Slowed luminance reaction times in cervical dystonia: disordered superior colliculus processin](https://onlinelibrary.wiley.com/doi/full/10.1002/mds.27975)g. Movement Disorders, 35(5), 877-880.

-   Field, M., Heather, N., Murphy, J. G., Stafford, T., Tucker, J. A., & Witkiewitz, K. (2020). [Recovery from addiction: Behavioral economics and value-based decision making](https://psyarxiv.com/rfjwu/). Psychology of Addictive Behaviors, 34(1), 182--193. https://doi.org/10.1037/adb0000518

-   Gyurkovics, M., Stafford, T., Levita, L. (2020). [Cognitive control across adolescence: Dynamic adjustments and mind-wandering](https://www.ncbi.nlm.nih.gov/pubmed/31599622). Journal of Experimental Psychology: General, 149(6), 1017--1031.

-   Tierney, W., Hardy III, J. H., Ebersole, C. R., Leavitt, K., Viganola, D., Clemente, E. G., ... & Hiring Decisions Forecasting Collaboration. (2020). [Creative destruction in science](https://www.sciencedirect.com/science/article/pii/S0749597820303678). Organizational Behavior and Human Decision Processes, 161, 291-309.

## 2019

-   Hampsey, E., Overton, P.G., Stafford, T. (2019). [Microsaccade rate as a measure of drug response](https://bop.unibe.ch/JEMR/article/view/JEMR.12.6.12). Journal of Eye Movement Research, 12(6). https://doi.org/10.16910/jemr.12.6.12   Open data/analysis scripts/etc: <https://osf.io/je8hf/>

-   Bannard, C., Leriche, M., Bandmann, O., Brown, C., Ferracane, E., Sánchez-Ferro, A., Obeso, J., Redgrave, P. and Stafford, T. (2019). [Reduced habit-driven errors in Parkinson's Disease](https://www.nature.com/articles/s41598-019-39294-z). Nature Scientific Reports 9(1), 3423. ([pre-print](https://psyarxiv.com/b25tf/))

-   Thirkettle, M., Thyoka, M., Fernandes, N., Gopalan, P., Stafford, T. Offiah, A.C. (2019). [Internet-based measurement of visual assessment skill of trainee radiologists: developing a sensitive tool](https://www.birpublications.org/doi/abs/10.1259/bjr.20180958). British Journal of Radiology, 92(1097), 20180958.

## 2018

-   Silberzahn, R. et al (2018). [Many analysts, one dataset: Making transparent how variations in analytical choices affect results](http://journals.sagepub.com/doi/full/10.1177/2515245917747646). Advances in Methods and Practices in Psychological Science, 1(3), 337-356. See also : '[Science isn't broken](https://fivethirtyeight.com/features/science-isnt-broken/)' and the [interactive visualisation by Mat Evans which allowed us to find an important confound in the source data](https://github.com/mathewzilla/redcard/blob/master/Crowdstorming_visualisation.ipynb).

-   Stafford, T., Holroyd, J., and Scaife, R. (2018). [Confronting bias in judging: A framework for addressing psychological biases in decision making](https://psyarxiv.com/nzskm). https://doi.org/10.31234/osf.io/nzskm

    -   See also: [Judiciary.uk: Biases in decision making](https://www.judiciary.uk/wp-content/uploads/2018/02/stafford-biases-in-decision-making-winter-2017.pdf).

-   Stafford, T. (2018). [Female chess players outperform expectations when playing men](http://journals.sagepub.com/doi/10.1177/0956797617736887). Psychological Science, 29(3), 429-436. (Preprint).

-   Pirrone, A., Azab, H., Hayden, B. Y., Stafford, T., and Marshall, J. A. R. (2018). [Evidence for the speed--value trade-off: Human and monkey decision making is magnitude sensitive](http://eprints.whiterose.ac.uk/109297/). Decision, 5(2), 129-142.

-   Panagiotidi, M., Overton, P.G., Stafford, T. (2018). [The relationship between ADHD traits and sensory sensitivity in the general population](https://www.sciencedirect.com/science/article/pii/S0010440X17302365). Comprehensive Psychiatry, 80, 179-185.

-   Kalfaoğlu, Ç., Stafford, T. and Milne, E. (2018). [Frontal theta band oscillations predict error correction and post error slowing in typing](https://www.ncbi.nlm.nih.gov/pubmed/28447844). Journal of Experimental Psychology: Human Perception and Performance, 44(1), 69-88.

## 2017

-   Stafford, T., Devlin, S., Sifa, R., and Drachen, A. (2017). [Exploration and skill acquisition in a major online game](https://mindmodeling.org/cogsci2017/papers/0615/paper0615.pdf). In Proceedings of The 39th Annual Meeting of the Cognitive Science Society.

-   Panagiotidi, M., Overton, P.G., Stafford, T. (2017). [Multisensory integration and ADHD-like traits: Evidence for an abnormal temporal integration window in ADHD](http://www.sciencedirect.com/science/article/pii/S000169181630302X). Acta Psychologica, 181, 10--17.

-   Panagiotidi, M., Overton, P.G., Stafford, T. (2017). [Co-occurrence of ASD and ADHD traits in the general population](http://eprints.staffs.ac.uk/3487/). Journal of Attentional Disorders.

-   Panagiotidi, M., Overton, P.G., Stafford, T. (2017). [Increased microsaccade rate in individuals with ADHD traits](https://bop.unibe.ch/index.php/JEMR/article/view/2963). Journal of Eye Movement Research. 10, 1.

-   Pirrone, A., Dickinson, A., Gomez, R., Stafford, T. and Milne, E. (2017). [Understanding perceptual judgement in autism spectrum disorder using the drift diffusion model](http://eprints.whiterose.ac.uk/107355/1/Perceptual%20Judgment%20in%20ASD%20final%20copy.pdf). Neuropsychology, 31 (2), 173--180.

-   Pirrone, A., Marshall, J. A., and Stafford, T. (2017). [A drift diffusion model account of the semantic congruity effect in a classification paradigm](https://jnc.psychopen.eu/article/view/79). Journal of Numerical Cognition, 3(1), 77--96.

-   Stafford, T. and Haasnoot, E. (2017). [Testing sleep consolidation in skill learning: a field study using an online game](http://onlinelibrary.wiley.com/wol1/doi/10.1111/tops.12232/abstract). Topics in Cognitive Science. 9(2), 485--496. ([data + code](https://osf.io/fckq8/))

-   Panagiotidi, M., Overton, P.G., Stafford, T. (2017). [Attention Deficit Hyperactivity Disorder-like traits and distractibility in the visual periphery](http://pec.sagepub.com/content/early/2016/11/28/0301006616681313.abstract). Perception, 46 (6), 665--678.

-   Holroyd, J., Scaife, R., Stafford, T. (2017). [What is implicit bias](http://onlinelibrary.wiley.com/doi/10.1111/phc3.12437/full)? Philosophy Compass, 12(10), e12437.

-   Holroyd, J., Scaife, R., Stafford, T. (2017). [Responsibility for Implicit Bias](http://onlinelibrary.wiley.com/doi/10.1111/phc3.12410/abstract). Philosophy Compass, 12(3), e12410.

## 2016


-   Bednark J., Reynolds J., Stafford T., Redgrave P. and Franz E. (2016). [Action experience and action discovery in medicated individuals with Parkinson's disease](http://journal.frontiersin.org/article/10.3389/fnhum.2016.00427). Frontiers in Human Neuroscience, 10, 427. DOI 10.3389/fnhum.2016.00427.

-   Bertram, C., and Stafford, T. (2016). [Improving training for sensory augmentation using the science of expertise](http://www.sciencedirect.com/science/article/pii/S0149763415300634). Neuroscience & Biobehavioral Reviews, 68, 234--244.

-   Lu, Y., Stafford, T., and Fox, C. (2016). [Maximum saliency bias in binocular fusion](http://www.tandfonline.com/doi/abs/10.1080/09540091.2016.1159181). Connection Science, 28(3),258-269.

## 2015


-   Thirkettle, M., Stafford, T., and Offiah, A. (2015). Internet Based Measurement of Visual Expertise in Radiological Skill. Perception, 44, 44-45.

## 2014

-   Stafford, T. and Dewar, M. (2014). [Tracing the trajectory of skill learning with a very large sample of online game players](http://pss.sagepub.com/content/25/2/511). Psychological Science, 25(2) 511--518. See also: [Data and analysis code](https://github.com/tomstafford/axongame).

-   Baldassarre, G., Stafford, T., Mirolli, M., Redgrave, P., Ryan, R. M., and Barto, A. (2014). [Intrinsic motivations and open-ended development in animals, humans, and robots: an overview](http://journal.frontiersin.org/Journal/10.3389/fpsyg.2014.00985/full). Frontiers in Psychology, 5(985). doi: 10.3389/fpsyg.2014.00985 (introduction to Special Topic we edited).

-   Kalfaoğlu, Ç & Stafford, T. (2014). [Performance breakdown effects dissociate from error detection effects in typing](http://www.tandfonline.com/eprint/neYR97ser5C3sFI8pcuT/full). The Quarterly Journal of Experimental Psychology, 67(3), 508--524.

-   Stafford, T. (2014). [The perspectival shift: how experiments on unconscious processing don't justify the claims made for them](http://journal.frontiersin.org/Journal/10.3389/fpsyg.2014.01067/full). Frontiers in Psychology, 5, 1067. doi:10.3389/fpsyg.2014.01067.

-   Stafford, T., Elgueta, H., Cameron, H. (2014).[ Students' engagement with a collaborative wiki tool predicts enhanced written exam performance](http://www.researchinlearningtechnology.net/index.php/rlt/article/view/22797). Research in Learning Technology, 22, 22797. doi:[10.3402/rlt.v22.22797](http://dx.doi.org/10.3402/rlt.v22.22797).

-   Pirrone, A., Stafford, T., and Marshall, J. A. R. (2014). [When natural selection should optimise speed-accuracy trade-offs](http://www.frontiersin.org/decision%20neuroscience/10.3389/fnins.2014.00073/full). Frontiers in Neuroscience, 8(73). doi: 10.3389/fnins.2014.00073.

-   Redgrave, P., Vautrelle, N., and Stafford, T. (2014). [Interpretive conundrums when practice doesn't always make perfect](http://www.ncbi.nlm.nih.gov/pubmed/24167063). Movement Disorders: Official Journal of the Movement Disorder Society, 29(1), 7-10. doi:10.1002/mds.25726.

-   Kerdegari, H., Kim, Y., Stafford, T., and Prescott, T. J. (2014, June). [Centralizing bias and the vibrotactile funnelling illusion on the forehead](https://eprints.whiterose.ac.uk/100435/1/Eurohaptic-final%20version-HK.pdf). In International Conference on Human Haptic Sensing and Touch Enabled Computer Applications (pp. 55-62). Springer, Berlin, Heidelberg.

## 2013

-   Bertram, C., Evans, M. H., Javaid, M., Stafford, T., and Prescott, T. (2013). Sensory augmentation with distal touch: the tactile helmet project. In Biomimetic and Biohybrid Systems (pp. 24-35). Springer Berlin Heidelberg.

-   Thirkettle, M., Walton, T., Redgrave, P., Gurney, K., and Stafford, T. (2013). [No learning where to go without first knowing where you're coming from: action discovery is trajectory, not endpoint based](http://www.frontiersin.org/cognitive_science/10.3389/fpsyg.2013.00638/abstract). Frontiers in Cognitive Science, 4:, 638. doi:10.3389/fpsyg.2013.00638.

-   Walton, T., Thirkettle, M., Redgrave, P., Gurney, K. N., and Stafford, T. (2013). [The discovery of novel actions is affected by very brief reinforcement delays and reinforcement modality](http://www.tandfonline.com/doi/full/10.1080/00222895.2013.806108). Journal of Motor Behavior, 45(4), 351--360.

-   Bednark, J. G., Reynolds, J. N. J., Stafford, T., Redgrave, P., and Franz, E. A. (2013). [Creating a movement heuristic for voluntary action: Electrophysiological correlates of movement-outcome learning](http://www.sciencedirect.com/science/article/pii/S0010945211003224). Cortex, 49(3), 771-780. doi:10.1016/j.cortex.2011.12.005.

-   Thirkettle, M., Walton, T., Shah, A., Gurney, K., Redgrave, P., and Stafford, T. (2013). [The path to learning: Action acquisition is impaired when visual reinforcement signals must first access cortex](http://www.sciencedirect.com/science/article/pii/S0166432813000429). Behavioural Brain Research, 243, 267--272. doi:10.1016/j.bbr.2013.01.023.


## 2012


-   Stafford, T., Thirkettle, M., Walton, T., Vautrelle, N., Hetherington, L., Port, M., Gurney, K.N., Redgrave, P. (2012), [A novel task for the investigation of action acquisition](http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0037749), PLoS One, 7(6), e37749.

-   Stafford, T. and Grimes, A. (2012). [Memory enhances the mere exposure effect](https://drive.google.com/file/d/1XuHvFVk3rbWHmuEHclPxFGSXSi8_Rp88/view?usp=sharing). (PDF, 626KB) Psychology & Marketing, 29, 12, 995--1003.

-   Stafford, T., and Bell, V. (2012). [Brain network: social media and the cognitive scientist](https://drive.google.com/file/d/1ouB70muf-9-XN_7RbeN86QQIU1tEn8lZ/view?usp=sharing). (PDF, 108KB) Trends in Cognitive Sciences, 16(10), 489--490. doi:10.1016/j.tics.2012.08.001.

## 2011

-   Stafford, T., & Gurney, K. N. (2011). [Additive factors do not imply discrete processing stages: a worked example using models of the Stroop Task](http://www.frontiersin.org/Cognitive_Science/10.3389/fpsyg.2011.00287/abstract). Frontiers in Psychology, 2. doi:10.3389/fpsyg.2011.00287.

-   Stafford, T., Ingram, L. and Gurney, K.N. (2011), [Pieron's Law holds during Stroop conflict: insights into the architecture of decision making](https://drive.google.com/file/d/19v6Bi6x01YBs5InJj8ALNNfhUP1ZrV6H/view?usp=sharing). (PDF, 374KB)  Cognitive Science 35, 1553--1566.

-   Yates, D.J. and Stafford, T. (2011), [Insights into the function and mechanism of saccadic decision making from targets scaled by an estimate of the cortical magnification factor](http://www.abrg.group.shef.ac.uk/!DATA/attachment/0102.Yates2011a.pdf), Cognitive Computation, 3, 89--93.


## Earlier key publications

-   Stafford, T. (2010). [How do we use computational models of cognitive processes?](https://drive.google.com/file/d/1U3JZPaUb_J-L-tj9t8CpevsvUTAcOyvr/view?usp=sharing) (PDF, 118KB) In Connectionist Models Of Neurocognition And Emergent Behaviour: From Theory to Applications. Proceedings of the 12th Neural Computation and Psychology Workshop, Birkbeck, University of London, 8-10 April 2010. World Scientific (pp. 326--342).

-   Stafford, T. (2009), [What use are computational models of cognitive processes?](https://drive.google.com/file/d/1KTWXcmsH9TWwVVagAfysf0ch-IQjzIDW/view?usp=sharing) (PDF, 56KB) In Mayor, J., Ruh, N.,  Plunkett, K. Connectionist Models of Behaviour and Cognition II: Proceedings of the 11th Neural Computation and Psychology Workshop. World Scientific.

-   Eiser, J. R., Stafford, T., Henneberry, J., and Catney, P. (2009). "Trust me, I'm a Scientist (Not a Developer)": [Perceived expertise and motives as predictors of trust in assessment of risk from contaminated land](https://drive.google.com/file/d/1mBtjfzW89lcLCWogK9ZYhIm3EJNFqCJq/view?usp=sharing). (PDF, 260KB)  Risk Analysis, 29(2), 288--297.

    -   see also [Why don't we trust the experts? (2016)](https://tomstafford.sites.sheffield.ac.uk/news/why-dont-we-trust-the-experts)

-   Stafford, T. and Gurney, K.N. (2007), [Biologically constrained action selection improves cognitive control in a model of the Stroop task](http://www.abrg.group.shef.ac.uk/!DATA/attachment/0046.stafford07.pdf), (External PDF) Philosophical Transactions of the Royal Society B: Biological Sciences, 362 (1485), 1671--1684.

-   Stafford, T. and Wilson, S. P. (2007), [Self-organisation can generate the discontinuities in the somatosensory map](https://drive.google.com/file/d/1IblZNhCxsEbgnL4K5x25qahwsXT5so4G/view?usp=sharing). (PDF, 347KB)  Neurocomputing, 70(10-12), 1932--1937.

-   Stafford, T. and Gurney, K. N. (2004), [The role of response mechanisms in determining reaction time performance: Pieron's Law revisited](https://drive.google.com/file/d/1173WABpGb9jbDOwU-i99X9zrU5szzlmL/view?usp=sharing). (PDF, 231KB)  Psychonomic Bulletin & Review, 11, 975--987.

-   Eiser, J. R., Fazio, R. H., Stafford, T. and Prescott, T. J. (2003), [Connectionist simulation of attitude learning: Asymmetries in the acquisition of positive and negative evaluations](https://drive.google.com/file/d/1bULXLeeUMv3wgq7g47JgLAZYfD_0ailg/view?usp=sharing). (PDF, 505KB)  Personality and Social Psychology Bulletin, 29, 1221--1235.


# Conference papers and posters

-   **Ambient rubbish: examining the attitudinal impact of incidental exposure to brand litter.** Grimes A, Stafford T and Roper S (2016), Academy of Marketing's 11th Global Brand Conference, Bradford University, UK

-   [**Linking total movement history to action learning**](http://www.google.com/url?q=http%3A%2F%2Ffigshare.com%2Farticles%2FLinking_total_movement_history_to_action_learning%2F892378&sa=D&sntz=1&usg=AOvVaw3ExoQVhh4BcI8upQL-gmdc). Stafford and Thirkettle. Poster presented at Reinforcement Learning and Decision Making 2013, 24--26 October, Princeton, USA

-   [**Testing theories of skill learning using a very large sample of online game players**](http://www.google.com/url?q=http%3A%2F%2Fmindmodeling.org%2Fcogsci2013%2F&sa=D&sntz=1&usg=AOvVaw25DG89Sfh2NZ8l9IK1qroA). Stafford & Dewar. Talk at the 35th Annual Meeting of the Cognitive Science Society, Berlin, Germany, 31 July 31 --3 August 2013

-   **The effect of acquisition of an internal forward model on an exploration task**. M. Dagioglou, J. M.Bugella, T. Walton, T. Stafford, P. Redgrave, R.C. Miall. Poster presented at the 22nd Annual Meeting of the Society for the Neural Control of Movement, 23--29 April 2012, Venice, Italy

-   [**Typing errors lead to increase in power and synchronization of theta oscillations**](https://drive.google.com/file/d/1Wu2oCkV5wyFZd_RjB33leGZI4R7drPMg/view?usp=sharing). (PNG, 923KB) Cigir Kalfaoglu, Tom Stafford and Elizabeth Milne. Poster presentation (by Kalfaoglu) in the British Association of Cognitive Neuroscience in Newcastle, UK on Wednesday the 11 April, 2012.

-   **Instruction to relax enhances visual search performance by altering eye movements.** David Yates and Tom Stafford. Oral Presentation (by Yates) at 34th European Conference on Visual Perception which will be held in Toulouse, France from Sunday 28th August to Thursday 1st September, 2011.

-   [**Visual search performance can be enhanced by instructions that alter eye movements**](https://drive.google.com/file/d/1dT4pXbJT-C1sBv5ORKyH623_ip-oqygg/view?usp=sharing).(PDF, 962KB)  David Yates and Tom Stafford. Poster Presentation (by Yates) at 16th European Conference on Eye Movements which will be held in Marseille, France from 21 --25 August 2011.

-   **Learning the long way round: action learning based on visual signals unavailable to the superior colliculus is impaired.** Martin Thirkettle, Tom Walton, Kevin Gurney, Peter Redgrave and Tom Stafford. Oral presentation (by Thirkettle) at 34th European Conference on Visual Perception which will be held in Toulouse, France from Sunday 28th August to Thursday 1st September 2011.

-   **What mistakes reveal about skilled performance: a study of touch-typing**. Cigir Kalfaoglu, Tom Stafford and Elizabeth Milne. Poster presentation (by Kalfaoglu) in the Experimental Psychologists Society Meeting in Oxford, UK from Wednesday the 13th to Friday the 15th of April, 2011.

-   [**Integrating** ](https://drive.google.com/file/d/1gakIKmUFR3HqYLjn2FnVGKkHJVcbYzzA/view?usp=sharing)[**a**](https://drive.google.com/file/d/1gakIKmUFR3HqYLjn2FnVGKkHJVcbYzzA/view?usp=sharing)[**ugmented** ](https://drive.google.com/file/d/1gakIKmUFR3HqYLjn2FnVGKkHJVcbYzzA/view?usp=sharing)[**s**](https://drive.google.com/file/d/1gakIKmUFR3HqYLjn2FnVGKkHJVcbYzzA/view?usp=sharing)[**enses into active perception: a framework**](https://drive.google.com/file/d/1gakIKmUFR3HqYLjn2FnVGKkHJVcbYzzA/view?usp=sharing)**.**  Stafford, T., Javaid, M, Mitchinson, B., Galloway, A.M.J., Prescott, T.J. (2011). Poster presented at Royal Society meeting on Active Touch Sensing at the Kavli Royal Society International Centre, 31 January -- 02 February, 2011

-   **Tracking the learning of actions:** **a****n evaluation of the frontal P3a component**. J.G. Bednark, E.A. Franz, T. Stafford, P. Redgrave, J.N.J. Reynolds. Society for Neuroscience Annual Meeting, 17-21 October 2009, Chicago.

-   [**Saccadic latency versus eccentricity for targets scaled by an estimate of the cortical magnification factor**](https://drive.google.com/file/d/1wipQkEDOefWmKfhq7_jIM-_ZRa49DRUt/view?usp=sharing). (PNG, 1.8MB)  Yates, D.J.; Stafford, T. 15th European Conference on Eye Movements, Southampton, 23--27 August, 2009.

-   [**The** ](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**n**](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**onconscious mere** ](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**e**](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**xposure effect with brand** ](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**l**](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**ogos: real but** ](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**e**](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing)[**lusive**](https://drive.google.com/file/d/1mYVVhmBOA2PhNn4fJcaAsRlClDRy1lhj/view?usp=sharing). (PDF, 2.6MB) Stafford, T; Grimes, A., Perkins, C. The 21st Annual Convention of the Association for Psychological Science, 22-24 May 2009, San Francisco, CA.

-   **What use are computational models of cognitive processes?**  Stafford, T. 11th Neural Computation and Psychology Workshop, Oxford, 16-18 July, 2008.

-   [**Self-organisation explains discontinuities in the somatosensory map**](https://drive.google.com/file/d/1LioNtU36rUpLpIXWa6P0ik02h6droGpw/view?usp=sharing). (PDF, 1MB)  Stafford, T. and Wilson, S.P. Fifteenth Annual Computational Neuroscience Meeting CNS. 2006, 16--20 July 2006.

-   [**The neural circuitry necessary for decision making by evidence accumulation**](https://drive.google.com/file/d/1MSAuCBqVtHuqE-kJdtEjLfqDLgud5AAM/view?usp=sharing).  Tom Stafford, Mark D. Humphries, Jonathan M. Chambers. Poster presented at the Computational Cognitive Neuroscience conference in Washington, DC, 11 October 2005.

-   **The basal ganglia as the selection mechanism in a cognitive task**. Stafford, T. and Gurney, K. (2005). In J. J. Bryson, T. J. Prescott and A. Seth (Eds.) Modelling natural action selection (pp. 77-83). AISB Press.

-   [**The basal ganglia as the selection mechanism in a cognitive task**](https://drive.google.com/file/d/11mUBgognVLh-1cS8XIoXYQLwWRwsCv5t/view?usp=sharing). (PNG, 1.4MB) Stafford, T. and Gurney, K. (2005). Poster presented at Modelling Natural Action Selection workshop in Edinburgh, July 2005.

-   **Learning under uncertainty: Manipulating and simulating the role of expectations.**  Eiser, Richard, Stafford, Tom, Shook, Natalie and Fazio, Russell. Paper presented at the 14th General Meeting of the European Association fo Experimental Social Psychology, Wurzburg, 19-23 July 2005.

-   **Acid tar lagoons: risks and sustainable remediation in an urban context.**  Catney, P., Lawson, N., Palaseanu-Lovejoy, M., Shaw, S., Smith, C., Stafford, T., Talbot, S., Hao, X. (2005, 1st of March 2005). Paper presented at the SUBR:IM conference, Natural History Museum, London.

-   **The Basal Ganglia provides an appropriate model for response selection in the Stroop task.**  Stafford, T. and Gurney, K.N. Poster presented at the Annual Conference of the BPS Cognitive Psychology Section at Essex, September 6th-8th, 2000.

# Other publications

-   Yates, D., and Stafford, T. (2017, October 1). [**'Cognitive strategy' in visual search: how it works and when it generalises**](https://www.google.com/url?q=https%3A%2F%2Fpsyarxiv.com%2F5dup8%2F&sa=D&sntz=1&usg=AOvVaw11ViqM96Lr3hnLbFR4Ppb3). https://doi.org/10.31234/osf.io/5dup8.

-   Stafford, T. (2009). [**Lessons from the campaign against Elsevier: "We won, but how did we win?"**](https://drive.google.com/file/d/1TK60znv37xBB0r-5LJhxY0IUeGKCHT6e/view?usp=sharing)[.](https://drive.google.com/file/d/1TK60znv37xBB0r-5LJhxY0IUeGKCHT6e/view?usp=sharing) (PDF, 168KB) *ACME: An International E-Journal for Critical Geographies*, 8(3), 494--504.

-   Stafford, T. (2008). [**Teaching questions rather than answers: inquiry-based learning on an MSc course**](https://drive.google.com/file/d/1ygxtidGmBfM-i0DJwBcqRf_GNL6yH32M/view?usp=sharing)**.** (PDF, 58KB) *HEA Psychology Network Newsletter*, Issue 46, January 2008. Available at: [http://www.psychology.heacademy.ac.uk/html/newsletter.asp](http://www.google.com/url?q=http%3A%2F%2Fwww.psychology.heacademy.ac.uk%2Fhtml%2Fnewsletter.asp&sa=D&sntz=1&usg=AOvVaw3ucom4XsicuL9yKSHQnXa6)

-   Stafford, T. and Martin, C.J. (2007). [**How to do a neuroscience lab class with 120 students**](https://drive.google.com/file/d/1N88oBScVw4zTZIx9xneIjCnHL0xRY0Ua/view?usp=sharing). (PDF, 62KB) *HEA Psychology Network Newsletter*, Issue 45, November 2007. Available at: [http://www.psychology.heacademy.ac.uk/html/newsletter.asp](http://www.google.com/url?q=http%3A%2F%2Fwww.psychology.heacademy.ac.uk%2Fhtml%2Fnewsletter.asp&sa=D&sntz=1&usg=AOvVaw3ucom4XsicuL9yKSHQnXa6)

-   Stafford, T. (2007). [Isn't it all just obvious?](http://www.google.com/url?q=http%3A%2F%2Fwww.bps.org.uk%2Fpublications%2Fthepsychologist%2Fsearch-the-psychologist-online.cfm%3Ffuseaction%3Dinc_psychologistdet%26ID%3D1145%26Publication_ID%3D1&sa=D&sntz=1&usg=AOvVaw2x3vJi_32e8EIdPmGIQeRW) *The Psychologist*, 20, 2, 94--95.

-   **The neural circuitry necessary for decision making by evidence accumulation**\
    Mark D. Humphries, Tom Stafford, Jonathan M. Chambers and Kevin N. Gurney\
    ABRG Technical Report number 5, May 2006. Department of Psychology, University of Sheffield, UK

-   Stafford, T. and Webb, M. (2006) **'What Is a Wiki (and How to Use One for Your Projects)'**. O'Reilly Network, 7 July 2006. Available at [http://www.oreillynet.com/pub/a/network/2006/07/07/what-is-a-wiki.html](http://www.google.com/url?q=http%3A%2F%2Fwww.oreillynet.com%2Fpub%2Fa%2Fnetwork%2F2006%2F07%2F07%2Fwhat-is-a-wiki.html&sa=D&sntz=1&usg=AOvVaw3Ra8vUj8t-t_0eMjG381sr)

-   Stafford, T. and Gurney, K. (2005). **The basal ganglia as the selection mechanism in a cognitive task**. In *J. J. Bryson, T. J. Prescott and A. Seth (Eds.) Modeling Natural Action Selection* (pp. 77--83). AISB Press.

-   Webb, M. and Stafford, T.(2004) **'Paying Attention (or Not) to the Flickr Daily Zeitgeist'.** O'Reilly Network, 6 December 2004. Available at [http://www.oreillynet.com/pub/a/network/2004/12/06/mndhcks_1.html](http://www.google.com/url?q=http%3A%2F%2Fwww.oreillynet.com%2Fpub%2Fa%2Fnetwork%2F2004%2F12%2F06%2Fmndhcks_1.html&sa=D&sntz=1&usg=AOvVaw0lsrLHn5iUCFWTFi8RMust)

-   Stafford, T. (2003). [**Integrating psychological and neuroscientific constraints in models of Stroop processing and action selection**](https://drive.google.com/file/d/1bPGdOXC6453IkNEJOhvwigpintO_c9eG/view?usp=sharing)**.** (PDF, 1MB) PhD Thesis, University of Sheffield.\
    [Abstract and contents only](https://drive.google.com/file/d/1CCKBfx3MqMcat2gUKaxL4At58-l_h3_S/view?usp=sharing) (PDF, 169KB)

-   Stafford, T. (2003). [**Psychology in the coffee shop**](http://www.google.com/url?q=http%3A%2F%2Fwww.idiolect.org.uk%2Fdocs%2Fjan04%2Fcoffee.pdf&sa=D&sntz=1&usg=AOvVaw31tI9HJmF3R-nIRUVcsaX2)**.** *The Psychologist*, 16(7), 358--359.

-   Stafford, T. (2000). [**Stroop interference: methodological problems and contrary data**](http://www.google.com/url?q=http%3A%2F%2Fpsycprints.ecs.soton.ac.uk%2Farchive%2F00000110%2F&sa=D&sntz=1&usg=AOvVaw25AMB1sxZcqBDAARA21Zu1)**,** *Psycoloquy*, 11, #110.


# Books and chapters

-   Stafford, T. (2011). [How do we use computational models of cognitive processes?](https://drive.google.com/file/d/1aXmvysI3PVNXGEdsMpAXunptvwUuez6h/view?usp=sharing) (PDF, 289KB) In E. Davelaar (eds) Connectionist Models Of Neurocognition And Emergent Behavior: Proceedings of the 12th Neural Computation and Psychology Workshop, 326--342. World Scientific.

-   Stafford, T. (2010).[ The Narrative Escape](http://mindhacks.com/2010/10/21/the-narrative-escape/), 40kbooks, Milan.

-   Moore, G & Stafford, T. (2010). [The Rough Guide Book of Brain Training](http://idiolect.org.uk/braintrain/).

-   Stafford, T. (2009) Hacking our tools for thought in Nold, C. (ed) Emotional Cartography: Technologies of the Self, 88-96. [emotionalcartography.net](http://emotionalcartography.net/)

-   Stafford, T. (2009). [What use are computational models of cognitive processes?](https://drive.google.com/file/d/19ZS4cAaAIlHcC0kTqOtJHAfox-4GRQlB/view?usp=sharing) (PDF, 132KB) In J. Mayor, N. Ruh and K. Plunkett (eds.) Connectionist Models of Behavior and Cognition II: Proceedings of the 11th Neural Computation and Psychology Workshop, 265--274. World Scientific.

-   Catney, P., Eiser, J.R., Henneberry, J. and Stafford, T. (2007) Democracy, Trust and Risk Related to Contaminated Sites in the UK, in: T. Dixon, M. Raco, P. Catney & D.N. Lerner (Eds.) Sustainable Brownfield Regeneration: Liveable Places from Problem Spaces. Oxford: Blackwells.

-   Stafford, T. and Gurney, K.N. (2006). Computational Models of Cognition. In An Introduction to Cognitive Psychology: Processes and Disorders. Second Edition. Ed. David Groome. Hove, UK: Psychology Press.

-   Stafford, T. and Webb, M. (2004). [Mind Hacks: Tips and Tricks for using your brain](http://www.mindhacks.com/). Sebastapol, CA: O'Reilly.