---
title: "Publications"
---

[Google scholar profile](https://scholar.google.co.uk/citations?hl=en&user=bMEna2UAAAAJ&view_op=list_works&sortby=pubdate), ORCID ID : [0000-0002-8089-9479](http://orcid.org/0000-0002-8089-9479)

# Theme highlights

--------------------

## Data intensive psychology: 

-   Panagiotidi, M., Zavlis, O., Jones, M., & Stafford, T. (2023). [The three-dimensional community structure of ADHD traits captured by the ASRS scale: An Exploratory Graph Analysis](http://doi.org/10.1002/mpr.1997). International Journal of Methods in Psychiatric Research.  http://doi.org/10.1002/mpr.1997

-   Stafford, T., and Vaci, N. (2022). [Maximizing the potential of digital games for understanding skill acquisition](https://doi.org/10.1177/09637214211057841). Current Directions in Psychological Science, 31(1), 49-55.  <https://doi.org/10.1177/09637214211057841> [[web/mobile version](https://journals.sagepub.com/doi/full/10.1177/09637214211057841)]

-   Bannard, C., Leriche, M., Bandmann, O., Brown, C., Ferracane, E., Sánchez-Ferro, A., Obeso, J., Redgrave, P. and Stafford, T. (2019). [Reduced habit-driven errors in Parkinson's Disease](https://www.nature.com/articles/s41598-019-39294-z). Nature Scientific Reports 9(1), 3423. ([pre-print](https://psyarxiv.com/b25tf/))

## Metaresearch

-   Jones, A., Stafford, T., & Petrovskaya, E. (under review). [Exploring the multiverse of analysis options for the Addiction Stroop](https://psyarxiv.com/prfu2/).

-   Stafford T, Rombach I, Hind D et al. (2023) [Where next for partial randomisation of research funding? The feasibility of RCTs and alternatives](https://wellcomeopenresearch.org/articles/8-309/v1) Wellcome Open Res 2023, 8:309 (https://doi.org/10.12688/wellcomeopenres.19565.1)

-   Bendiscioli, Sandra; Firpo, Teo; Bravo-Biosca, Albert; Czibor, Eszter; Garfinkel, Michele; Stafford, Tom; et al. (2022): [The Experimental Research Funder's Handbook](https://rori.figshare.com/articles/report/The_experimental_research_funder_s_handbook_final_version_/19459328) (Revised edition, June 2022, ISBN 978-1-7397102-0-0). Research on Research Institute. Report. https://doi.org/10.6084/m9.figshare.19459328.v2

-   Silberzahn, R. et al (2018). [Many analysts, one dataset: Making transparent how variations in analytical choices affect results](http://journals.sagepub.com/doi/full/10.1177/2515245917747646). Advances in Methods and Practices in Psychological Science, 1(3), 337-356. 

    -   See also : '[Science isn't broken](https://fivethirtyeight.com/features/science-isnt-broken/)' and the [interactive visualisation by Mat Evans which allowed us to find an important confound in the source data](https://github.com/mathewzilla/redcard/blob/master/Crowdstorming_visualisation.ipynb).

    -   Ploner, S., & Stafford, T. (2021). [How analysis strategy affects analysis results: Assessing results space and structure of Silberzahn et al. (2018) through model specification](https://osf.io/preprints/psyarxiv/nzskm). Retrieved from osf.io/preprints/psyarxiv/b2hm7

## Decision making & reasoning

-   Stafford, T., Pirrone, A., Croucher, M., and Krystalli, A. (2020). [Quantifying the benefits of using decision models with response time and accuracy data](https://link.springer.com/article/10.3758/s13428-020-01372-w). Behaviour Research Methods, 52, 2142--2155. [doi.org/10.3758/s13428-020-01372-w](https://doi.org/10.3758/s13428-020-01372-w) (pre-print, [web/mobile version](https://idiolect.org.uk/papers/stafford2020/))

-   Brand, C. O., Brady, D., & Stafford, T. (2023, June 27). [The Ideological Turing Test: a behavioural measure of open-mindedness and perspective-taking](https://psyarxiv.com/2e9wn). https://doi.org/10.31234/osf.io/2e9wn

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2023). [DeliData: A dataset for deliberation in multi-party problem solving](https://dl.acm.org/doi/10.1145/3610056). Proceedings of the ACM on Human-Computer Interaction, CSCW. https://doi.org/10.1145/3610056 [[arXiv](https://arxiv.org/abs/2108.05271)]

-   Karadzhov, G., Stafford, T., and Vlachos, A. (2022). [What makes you change your mind? An empirical investigation in online group decision-making conversations](https://www.delibot.xyz/publications/). arXiv preprint [arXiv:2207.12035](https://arxiv.org/abs/2207.12035)

    -   -   See also: [delibot.xyz](https://www.delibot.xyz/)

-   de Kock, C., Stafford, T., & Vlachos, A. (2022). [How to disagree well: Investigating the dispute tactics used on Wikipedia](https://arxiv.org/abs/2212.08353). arXiv preprint arXiv:2212.08353.