---
title: "Tom Stafford - The department’s first Director of Public Engagement"
source: "https://tomstafford.sites.sheffield.ac.uk/news/the-departments-first-director-of-public-engagement"
date: "2013-07-05"
---

# The department's first Director of Public Engagement 

[Back to News](/news)

5 July 2013

I am now the department's first Director of Public Engagement. It's a position which encompasses my previous admin roles of media liaison, website coordinator, faculty external relations and marketing contact, outreach and widening participation champion and academic organiser\* of the internal and external seminar series and of our inaugural lectures for new professors.

The creation of the public engagement role brings no particular new powers or benefits, apart from I get to be director of something, which flatters me. What I hope it does do is signal that the department takes its duties for public service seriously, and give me remit to promote the kind of activities I believe the department should do more of. At this point, I wanted to write something about what, for me, the principles of public engagement are.

First, public engagement signifies a kind of public service which is wider than the 'Impact' agenda. At the moment the government funding model for universities has prioritised measurable economic benefits which arise from specific research outputs (ie from academic papers).

This means that if you publish a research paper on widget manufacture, and a local business consequently is able to up its widget production from £100,000 of widgets per year, to £200,000 of widgets you have had impact.

If you spend thirty years synthesising the values and methods of a domain of enquiry and write a textbook (or appear on television like Brian Cox) talking about your discipline you have had no impact. What you are doing is not based on a specific unit of research, the outcomes are unclear and hard to measure.

For me public engagement captures many of the range of nonspecific, hard to measure benefits of universities. We are in an immensely privileged position within the University to be able to specialise, to dedicate ourselves to thoroughness, scholarship, discussion and fairness. There is a societal benefit to having spaces committed to these values, it would be a shame if those were eroded because [the benefits were hard to measure](http://en.wikipedia.org/wiki/McNamara_fallacy).

So I'm pleased that the University of Sheffield is working hard to celebrate the cultural and intellectual value of universities, reflected in the good work of our Public Engagement with the Research team and things like the [Civic University project](http://www.sheffield.ac.uk/civic).

Second, 'public engagement' is not 'public understanding', nor is it science communication. These two are both wonderful things, in a limited sense, but we're not here to bludgeon the public with things we think they should understand. Public engagement means talking with people outside of the department, not just telling them things.

Third and finally, there are many publics, rather than one public. Public, for the Psychology Department, means everyone who isn't a student or colleague. Within that group there will be many different interests - specialists and generalists, bystanders and activists.

If we cater our engagement for a 'general public' we're going to miss out on the opportunities to engage with specific individuals and groups in ways that mean our unique strengths as a department can be fully taken advantage of.

That's probably enough of the theory. In the immediate future I'm going to concentrate on finding out more about what people in our department already do in terms of public engagement, and pursue a few specific plans:

-   Making sure the department supports the [Civic University project](http://www.sheffield.ac.uk/civic).

-   Growing our new schools programme.

-   Organising a set of Inaugural lectures for our new professors.

-   Hopefully some events for the upcoming [Off The Shelf festival](http://www.welcometosheffield.co.uk/visit/off-the-shelf) in Sheffield.

Watch this space, as they say.

\* 'Academic organiser' of course means that all the real organising is done by our wonderful support staff. For the seminars that's Liz Carl specifically - thanks Liz!
