---
title: "Tom Stafford - We are European scholars"
source: "https://tomstafford.sites.sheffield.ac.uk/news/we-are-european-scholars"
date: "2016-07-05"
---

# We are European scholars 

[Back to News](/news)

5 July 2016

I am British, but consider myself a European scholar. At the start of my time as a lecturer at the University I was lucky enough to be part of an [EU funded project on learning in robots](http://www.im-clever.eu/). With that project I worked with brilliant colleagues around the EU, as well as being able to do the piece of work I regard as [my single most important scientific contribution](/news/new-paper-the-path-to-learning-action-acquisition-is-impaired).

It was EU projects like this which inspired the foundation of [Sheffield Robotics](http://www.sheffieldrobotics.ac.uk/), a collaboration between the two Universities in Sheffield which aims to define the future of a technology vital to manufacturing in the UK. Two British PhD students I supervised during this project went on to start a business and a third, from Cyprus, did work with me that led to a [major grant from the Michael J Fox Foundation for research into Parkinson's Disease](/news/new-grant-reduced-habitual-intrusions-an-early-marker-for-parkinsons). This brings US funding into the UK to allow me to work with colleagues in Spain and the US on a health issue that will affect 1 in 500 of us - over 120,000 people in the UK.

Since then I have had two more brilliant PhD students from the EU. One, from Greece, completed a PhD on differences in sensory processing in ADHD and has since gone to work in industry, applying her research skills for a company based in Manchester.

The other, an Italian, is currently writing up and considering job opportunities from around the world. My hope is that we'll be able to keep him in the UK, where he'll be able to continue to contribute to the research environment that make British universities the best in the world.

The UK needs universities to train our young people, to contribute to public life and to investigate the world around us and within us. The UK's universities need Europe.

I am a European scholar. We are European scholars at the University of Sheffield. Without our European links and colleagues we, and the UK, would be immeasurably impoverished.

Written in support of [yesterday's call](https://www.sheffield.ac.uk/vc/office/updates/we-are-european-scholars-1.587949) by the University of Sheffield's Vice-Chancellor.
