---
title: "Tom Stafford - Internship: Public engagement coordinator"
source: "https://tomstafford.sites.sheffield.ac.uk/news/internship-public-engagement-coordinator"
date: "2016-10-12"
---

# Internship: Public engagement coordinator 

[Back to News](/news)

12 October 2016

If you are a recent graduate of the University of Sheffield, then you can apply for this paid internship as Public engagement coordinator, working with me in the Department of Psychology. Here's what we want to do:

"Help the Department of Psychology engage with the public. Our vision is to arrange, promote, run and record a series of 'TED'-style talks for psychology at Sheffield. These will be our chance to reach hundreds of college-age students - both those in our majority recruitment demographic and those from under-represented backgrounds."

Who we're looking for:

"The ideal candidate will be enthusiastic for what universities can offer society, and vice versa. You will have an appreciation of the concerns of applicants to the University - especially those from 'widening participation' backgrounds - and be capable of keeping track of a complex set of tasks.

"In this internship you will learn to organise and promote large events, to put scholarship in a wider context and see how issues in people's everyday lives connect to the work we do in the Department of Psychology. You will practice writing in an engaging and accessible way and get to work with people across the University and the region."

It's six months, full time, paid.

[Job overview (PDF, 37KB)](https://drive.google.com/file/d/1Wfb7r8y2nmgMoqbtIEWAEdTApY3odCpf/view?usp=sharing)

[Job description (PDF, 517KB)](https://drive.google.com/file/d/1-MPdeDcVk47HcDBtG9i16u-128vilE6j/view?usp=sharing)

To apply go to [careerconnect.sheffield.ac.uk](https://careerconnect.sheffield.ac.uk/) and enter reference UOS014640. To be eligible you need to have graduated from a University of Sheffield undergraduate degree in 2016. Closing date: 4 of November 2016.
