---
title: "Tom Stafford - Seminar - Framing effects in the field: Evidence from two million bets"
source: "https://tomstafford.sites.sheffield.ac.uk/news/seminar-framing-effects-in-the-field-evidence-from-two-million-bets"
date: "2017-11-01"
---

# Seminar - Framing effects in the field: Evidence from two million bets 

[Back to News](/news)

1 November 2017

Friday 8 December, 1pm, The Diamond, LT2.

[Alasdair Brown](https://www.uea.ac.uk/economics/people/profile/alasdair-brown), School of Economics, UEA.

Abstract: Psychologists and economists have often found that risky choices can be affected by the way that the gamble is presented or framed. We analyse two million tennis bets over a six-year period to analyse

1.  whether frames are important in a real high-stakes environment, and

2.  whether individuals pay a premium in order to avoid certain frames.

In this betting market, the same asset can be traded at two different prices at precisely the same time. The only difference is the way that the two bets are framed. The fact that these isomorphic bets arise naturally allows us to examine a scale of activity beyond even the most well-funded experiments.

We find that bettors make frequent mistakes, choosing the worse of the two bets in 29% of cases. Bettors display a (costly) aversion to the framing of bets as high risk, but there is little evidence of loss aversion. This suggests that individuals are indeed susceptible to framing manipulations in real-world situations, but not in the way predicted by prospect theory.

Part of the [Psychology department seminar series](https://www.uea.ac.uk/economics/people/profile/alasdair-brown). Tom Stafford is the host.
