---
title: "Tom Stafford - The Choice Engine"
source: "https://tomstafford.sites.sheffield.ac.uk/news/the-choice-engine"
date: "2018-09-20"
---

# The Choice Engine 

[Back to News](/news)

20 September 2018

How and why do we choose? Are our choices free, or determined by our past, our brains or our environment? Are our choices ours?

The Choice Engine is an interactive essay which unfolds according to what you choose to read about next.

Experience it by visiting [\@ChoiceEngine on Twitter](https://twitter.com/@ChoiceEngine).

We'll be discussing the project and the ideas behind it as part of the [Festival of the Mind](https://festivalofthemind.group.shef.ac.uk/) at 4pm on 25 September in the Speigeltent, Barker's Pool. This event brings together the team behind the Choice Engine and scholars of choice from psychology, neuroscience and the arts to discuss choice and free will.

Featuring

-   Jon Cannon, Designer - [joncannon.co.uk](http://www.joncannon.co.uk/)

-   Tom Stafford, Department of Psychology

-   Helena Ifill, School of English

And the chance for audience questions and interventions.

This event is free, all welcome.

[Event details](https://festivalofthemind.group.shef.ac.uk/the-choice-engine-talk/)
