---
title: "Tom Stafford - PhD opportunity: Informing citizens?"
source: "https://tomstafford.sites.sheffield.ac.uk/news/phd-opportunity-informing-citizens"
date: "2021-01-26"
---

# PhD opportunity: Informing citizens? Effects of imprints on digital political advertising 

[Back to News](/news)

26 January 2021

A fully funded PhD position starting October 2021. Application deadline: 12 March 2021, interviews: 26 March.

Supervised by Dr Tom Stafford, Department of Psychology and Dr Kate Dommett from the Department of Politics at the University of Sheffield, UK and in collaboration with the Electoral Reform Society (where the student will intern during their studies). The studentship will run alongside our Leverhulme Trust project, 'Understanding online political advertising: Perceptions, uses and regulation'.

As well as doctoral training in experimental psychology, advanced training in quantitative methods and open research, experience of interdisciplinary and policy engaged research, this studentship also comes with an opportunity to complete a MSc in Research Methods if you are coming straight from an undergraduate degree.

Informal enquiries are welcome by email.

## Project outline 

Political campaigning is increasingly carried out online, affording campaigners new possibilities for targeting and customisation of campaign material to different audiences.

These developments have changed the information landscape, having consequences for the democratic ideal of an informed citizenry. As a consequence, policy makers have argued that voters need to be given additional information through transparency disclosures, aka \'imprints\', with Minister Chloe Smith arguing that:

"Democracy must work for the people - and empowering our citizens to participate makes our country stronger. However, there is growing concern about the transparency of the sources of political campaigning online, which is starting to have a negative impact on trust and confidence in our elections and democracy" (Cabinet Office, 2020, p.7)

Whilst the Government has begun to pursue policies designed to boost transparency, the impact of using mandatory information disclosures on online political campaign materials ("digital imprints") on public attitudes and behaviour is unknown, making it unclear whether attempts to inform citizens will boost public confidence and trust, or result in 'backfire' effects.

Developed in partnership with the Electoral Reform Society (ERS), who have an active research programme on voter information and digital campaigning, this studentship will use survey and experimental designs to explore the effect of different regulatory responses designed to promote transparency and an informed citizenry.

The student will test the impact of different possible digital imprints on voter response. Of interest is how voters use imprints to inform their interpretation of specific pieces of political information, eg digital campaign adverts. The project is also concerned with the overall impact on trust and confidence in political actors and the democratic system. The student will identify best practice for future regulation and policy design.

Reference: [Cabinet Office (2020) Transparency in digital campaigning: Technical consultation on digital imprints](https://www.gov.uk/government/consultations/transparency-in-digital-campaigning-technical-consultation-on-digital-imprints)

## More information 

This project is funded by the [ESRC WRDTP](https://wrdtp.ac.uk/studentships/). Fees are paid at the UK level and a stipend of £15,285/year provided, plus additional funds to support research training.

The award is available on either a 1+3 or +3 basis. A 1+3 studentship provides funding for four years, completing the MA in Social Research in the first year, followed by three years of research funding for a PhD. A +3 studentship provides funding for three years of PhD; this is only available to candidates who already have an MA in Social Research or a comparable masters in research methods.

[Additional details on](https://wrdtp.ac.uk/studentships/.) [wrdtp.ac.uk](https://wrdtp.ac.uk/studentships/.)

The student needs to commence their studies on 1 October 2021.

Eligibility: The candidate should have a strong academic background in psychology, with a First or strong 2:1 undergraduate degree predicted or obtained.

Please direct any questions about eligibility to [pgr-scholarships@sheffield.ac.uk](mailto:pgr-scholarships@sheffield.ac.uk)

Links: [FindAPhD](https://www.findaphd.com/phds/project/informing-citizens-effects-of-imprints-on-digital-political-advertising/?p129925)

## Apply 

Please email [t.stafford@sheffield.ac.uk](mailto:t.stafford@sheffield.ac.uk) by the deadline with:

-   A CV (one page); highlight any relevant project work.

-   A cover letter explaining why you want to do a PhD and this PhD in particular (one page); state whether you are applying for the 1+3 or +3 route.

-   A proposal for how the effect of imprints on public confidence and trust could be investigated using the tools of experiment psychology (no more than two pages). This will introduce your own ideas, including brief details on both rationale and research methodology.

## References 

For wider literature introducing the topic of political advertising and it's democratic significance see:

Barnard, L. and Kreiss, D. (2013) 'A research agenda for online advertising: Surveying campaign practices, 2000-2012', International Journal of Communication, 2046-2066.

Dommett, K. (2019) 'The rise of online political advertising', Political Insight, 10(4).

Dommett, K. and Power, S. (2019) 'The political economy of Facebook advertising: Election spending, regulation and targeting online', The Political Quarterly, 90(2), 257-265.

Kim, T., Barasz, K. and John, L. (2018) 'Why am I seeing this ad? The effect of ad transparency on ad effectiveness', Journal of Consumer Research, 45(5): 906-932. [https://doi.org/10.1093/jcr/ucy039](https://doi.org/10.1093/jcr/ucy039)
